[features]
seeds = false
skip-lint = false
[programs.localnet]
contract = "B6pbdUp5BMFHXVcytnWnNpwnGrMDDeFiaqPzMwcsPK9o"

[registry]
url = "https://solana-pswap.pages.dev"

[provider]
cluster = "localnet"
wallet = "/home/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
