[features]
seeds = false
skip-lint = false
[programs.localnet]
contract = "4vUKDt1E2HSTP22d8LYu1KGUoUtREDxAi938FMqTdCD2"

[registry]
url = "https://solana-pswap.pages.dev"

[provider]
cluster = "localnet"
wallet = "/home/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
